/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellTerminalsRouteImport } from './routes/_shell.terminals'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellSessionsRouteImport } from './routes/_shell.sessions'
import { Route as ShellSessionsIndexRouteImport } from './routes/_shell.sessions.index'
import { Route as ShellSessionsSessionIdRouteImport } from './routes/_shell.sessions.$sessionId'
import { Route as ShellProjectsProjectIdRouteImport } from './routes/_shell.projects.$projectId'
import { Route as ShellProjectsProjectIdSettingsRouteImport } from './routes/_shell.projects.$projectId_.settings'
import { Route as ShellProjectsProjectIdSessionsSessionIdRouteImport } from './routes/_shell.projects.$projectId_.sessions.$sessionId'
import { Route as ShellHostHostIdSessionSessionIdRouteImport } from './routes/_shell.host.$hostId.session.$sessionId'
import { Route as ShellHostHostIdProjectProjectIdSessionSessionIdRouteImport } from './routes/_shell.host.$hostId.project.$projectId.session.$sessionId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTerminalsRoute = ShellTerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSessionsRoute = ShellSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSessionsIndexRoute = ShellSessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellSessionsRoute,
} as any)
const ShellSessionsSessionIdRoute = ShellSessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ShellSessionsRoute,
} as any)
const ShellProjectsProjectIdRoute = ShellProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsProjectIdSettingsRoute =
  ShellProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId_/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellProjectsProjectIdSessionsSessionIdRoute =
  ShellProjectsProjectIdSessionsSessionIdRouteImport.update({
    id: '/projects/$projectId_/sessions/$sessionId',
    path: '/projects/$projectId/sessions/$sessionId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellHostHostIdSessionSessionIdRoute =
  ShellHostHostIdSessionSessionIdRouteImport.update({
    id: '/host/$hostId/session/$sessionId',
    path: '/host/$hostId/session/$sessionId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellHostHostIdProjectProjectIdSessionSessionIdRoute =
  ShellHostHostIdProjectProjectIdSessionSessionIdRouteImport.update({
    id: '/host/$hostId/project/$projectId/session/$sessionId',
    path: '/host/$hostId/project/$projectId/session/$sessionId',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/sessions': typeof ShellSessionsRouteWithChildren
  '/settings': typeof ShellSettingsRoute
  '/terminals': typeof ShellTerminalsRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/sessions/': typeof ShellSessionsIndexRoute
  '/projects/$projectId/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/host/$hostId/session/$sessionId': typeof ShellHostHostIdSessionSessionIdRoute
  '/projects/$projectId/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
  '/host/$hostId/project/$projectId/session/$sessionId': typeof ShellHostHostIdProjectProjectIdSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof ShellSettingsRoute
  '/terminals': typeof ShellTerminalsRoute
  '/': typeof ShellIndexRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/sessions': typeof ShellSessionsIndexRoute
  '/projects/$projectId/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/host/$hostId/session/$sessionId': typeof ShellHostHostIdSessionSessionIdRoute
  '/projects/$projectId/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
  '/host/$hostId/project/$projectId/session/$sessionId': typeof ShellHostHostIdProjectProjectIdSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/sessions': typeof ShellSessionsRouteWithChildren
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/terminals': typeof ShellTerminalsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/_shell/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/_shell/sessions/': typeof ShellSessionsIndexRoute
  '/_shell/projects/$projectId_/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/_shell/host/$hostId/session/$sessionId': typeof ShellHostHostIdSessionSessionIdRoute
  '/_shell/projects/$projectId_/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
  '/_shell/host/$hostId/project/$projectId/session/$sessionId': typeof ShellHostHostIdProjectProjectIdSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sessions'
    | '/settings'
    | '/terminals'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/sessions/'
    | '/projects/$projectId/settings'
    | '/host/$hostId/session/$sessionId'
    | '/projects/$projectId/sessions/$sessionId'
    | '/host/$hostId/project/$projectId/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/terminals'
    | '/'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/sessions'
    | '/projects/$projectId/settings'
    | '/host/$hostId/session/$sessionId'
    | '/projects/$projectId/sessions/$sessionId'
    | '/host/$hostId/project/$projectId/session/$sessionId'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/sessions'
    | '/_shell/settings'
    | '/_shell/terminals'
    | '/_shell/'
    | '/_shell/projects/$projectId'
    | '/_shell/sessions/$sessionId'
    | '/_shell/sessions/'
    | '/_shell/projects/$projectId_/settings'
    | '/_shell/host/$hostId/session/$sessionId'
    | '/_shell/projects/$projectId_/sessions/$sessionId'
    | '/_shell/host/$hostId/project/$projectId/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/terminals': {
      id: '/_shell/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof ShellTerminalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sessions': {
      id: '/_shell/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof ShellSessionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sessions/': {
      id: '/_shell/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof ShellSessionsIndexRouteImport
      parentRoute: typeof ShellSessionsRoute
    }
    '/_shell/sessions/$sessionId': {
      id: '/_shell/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof ShellSessionsSessionIdRouteImport
      parentRoute: typeof ShellSessionsRoute
    }
    '/_shell/projects/$projectId': {
      id: '/_shell/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ShellProjectsProjectIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId_/settings': {
      id: '/_shell/projects/$projectId_/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ShellProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId_/sessions/$sessionId': {
      id: '/_shell/projects/$projectId_/sessions/$sessionId'
      path: '/projects/$projectId/sessions/$sessionId'
      fullPath: '/projects/$projectId/sessions/$sessionId'
      preLoaderRoute: typeof ShellProjectsProjectIdSessionsSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/host/$hostId/session/$sessionId': {
      id: '/_shell/host/$hostId/session/$sessionId'
      path: '/host/$hostId/session/$sessionId'
      fullPath: '/host/$hostId/session/$sessionId'
      preLoaderRoute: typeof ShellHostHostIdSessionSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/host/$hostId/project/$projectId/session/$sessionId': {
      id: '/_shell/host/$hostId/project/$projectId/session/$sessionId'
      path: '/host/$hostId/project/$projectId/session/$sessionId'
      fullPath: '/host/$hostId/project/$projectId/session/$sessionId'
      preLoaderRoute: typeof ShellHostHostIdProjectProjectIdSessionSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellSessionsRouteChildren {
  ShellSessionsSessionIdRoute: typeof ShellSessionsSessionIdRoute
  ShellSessionsIndexRoute: typeof ShellSessionsIndexRoute
}

const ShellSessionsRouteChildren: ShellSessionsRouteChildren = {
  ShellSessionsSessionIdRoute: ShellSessionsSessionIdRoute,
  ShellSessionsIndexRoute: ShellSessionsIndexRoute,
}

const ShellSessionsRouteWithChildren = ShellSessionsRoute._addFileChildren(
  ShellSessionsRouteChildren,
)

interface ShellRouteChildren {
  ShellSessionsRoute: typeof ShellSessionsRouteWithChildren
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTerminalsRoute: typeof ShellTerminalsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellProjectsProjectIdRoute: typeof ShellProjectsProjectIdRoute
  ShellProjectsProjectIdSettingsRoute: typeof ShellProjectsProjectIdSettingsRoute
  ShellHostHostIdSessionSessionIdRoute: typeof ShellHostHostIdSessionSessionIdRoute
  ShellProjectsProjectIdSessionsSessionIdRoute: typeof ShellProjectsProjectIdSessionsSessionIdRoute
  ShellHostHostIdProjectProjectIdSessionSessionIdRoute: typeof ShellHostHostIdProjectProjectIdSessionSessionIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellSessionsRoute: ShellSessionsRouteWithChildren,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTerminalsRoute: ShellTerminalsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellProjectsProjectIdRoute: ShellProjectsProjectIdRoute,
  ShellProjectsProjectIdSettingsRoute: ShellProjectsProjectIdSettingsRoute,
  ShellHostHostIdSessionSessionIdRoute: ShellHostHostIdSessionSessionIdRoute,
  ShellProjectsProjectIdSessionsSessionIdRoute:
    ShellProjectsProjectIdSessionsSessionIdRoute,
  ShellHostHostIdProjectProjectIdSessionSessionIdRoute:
    ShellHostHostIdProjectProjectIdSessionSessionIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
